doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '10.1'
        charset: utf8
        url: 'postgresql://application:123456@172.18.0.1:9601/apteka'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            UserService:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/UserService'
                prefix: 'Xyz\Akulov\Service\UserService\Entity'
                alias: UserService
            TaskService:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/TaskService'
                prefix: 'Xyz\Akulov\Service\TaskService\Entity'
                alias: TaskService
            FileService:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/FileService'
                prefix: 'Xyz\Akulov\Service\FileService\Entity'
                alias: FileService
