security:
    encoders:
        Symfony\Component\Security\Core\User\User: sha256

    providers:
        common:
            id: apteka.symfony.extension.security.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        customer_personal_area:
            pattern: ^/customer-personal-area/
            guard:
                authenticators:
                    - apteka.symfony.extension.security.user_authenticator

        pharmacy_personal_area:
            pattern: ^/pharmacy-personal-area/
            guard:
                authenticators:
                    - apteka.symfony.extension.security.user_authenticator

        public:
            anonymous: ~
            guard:
                authenticators:
                    - apteka.symfony.extension.security.user_authenticator

    access_control:
        - { path: ^/customer-personal-area/, roles: [ROLE_ROOT, ROLE_CUSTOMER] }
        - { path: ^/pharmacy-personal-area/, roles: [ROLE_ROOT, ROLE_PHARMACY] }
