search:
    path: /
    defaults:
        _controller: apteka.controller.index:search

catalog:
    path: /catalog
    defaults:
        _controller: apteka.controller.index:catalog

authorization:
    path: /authorization
    defaults:
        _controller: apteka.controller.user:authorization

customer_registration:
    path: /registration
    defaults:
        _controller: apteka.controller.user:customerRegistration

customer_personal_area_index:
    path: /customer-personal-area/
    defaults:
        _controller: apteka.controller.customer_personal_area.index:index

pharmacy_registration:
    path: /pharmacy-registration
    defaults:
        _controller: apteka.controller.user:pharmacyRegistration

pharmacy_personal_area_index:
    path: /pharmacy-personal-area/
    defaults:
        _controller: apteka.controller.pharmacy_personal_area.index:index

pharmacy_personal_area_stock_upload:
    path: /pharmacy-personal-area/stock-upload
    defaults:
        _controller: apteka.controller.pharmacy_personal_area.stock:upload

pharmacy_personal_area_stock_list:
    path: /pharmacy-personal-area/stock-uploads-list
    defaults:
        _controller: apteka.controller.pharmacy_personal_area.stock:stocksUploadsList
