# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'ru'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Xyz\Akulov\Apteka\:
        resource: '../src/Apteka/*'
        exclude: '../src/Apteka/{Entity,Migrations,Tests}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Xyz\Akulov\Apteka\Controller\:
        resource: '../src/Apteka/Controller'
        tags: ['controller.service_arguments']

    apteka.redis:
        class: Redis
        calls:
            - [connect, ['172.18.0.1', '9602']]

    Xyz\Akulov\Common\Service\UserService\UserServiceInterface:
        class: Xyz\Akulov\Common\Service\UserService\UserService
        public: true
        arguments:
          - '@Doctrine\ORM\EntityManagerInterface'
          - '@validator.mapping.class_metadata_factory'
          - '@apteka.redis'

