parameters:
    locale: 'ru'

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    apteka.infrastructure.redis:
        class: Redis
        calls:
            - [connect, ['172.18.0.1', '9602']]

    apteka.symfony.extension.security.user_authenticator:
        class: Xyz\Akulov\Symfony\Service\UserService\Security\UserAuthenticator
        arguments:
            - '@router'
            - 'authorization'

    apteka.symfony.extension.security.user_provider:
        class: Xyz\Akulov\Symfony\Service\UserService\Security\UserProvider
        arguments:
            - '@apteka.service.user'

    apteka.symfony.twig.extantion.units_of_information:
        class: Xyz\Akulov\Symfony\TwigExtension\UnitsOfInformationExtension
        tags:
            - { name: twig.extension }

    apteka.listener.user_controller_redirect:
        class: Xyz\Akulov\Apteka\Symfony\Listener\UserControllerRedirect
        arguments:
            - '@apteka.service.user'
            - '@router'
        tags:
            - {name: kernel.event_listener, event: kernel.controller, method: onKernelController}

    apteka.controller.index:
        public: true
        class: Xyz\Akulov\Apteka\Symfony\Controller\IndexController

    apteka.controller.user:
        public: true
        class: Xyz\Akulov\Apteka\Symfony\Controller\UserController
        arguments:
            - '@apteka.service.user'

    apteka.controller.customer_personal_area.index:
        public: true
        class: Xyz\Akulov\Apteka\Symfony\Controller\CustomerPersonalArea\IndexController

    apteka.controller.pharmacy_personal_area.index:
        public: true
        class: Xyz\Akulov\Apteka\Symfony\Controller\PharmacyPersonalArea\IndexController

    apteka.controller.pharmacy_personal_area.stock:
        public: true
        class: Xyz\Akulov\Apteka\Symfony\Controller\PharmacyPersonalArea\StockController
        arguments:
            - '@apteka.service.pharmacy_stock'

    apteka.service.user:
        class: Xyz\Akulov\Symfony\Service\UserService\UserService
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@validator.mapping.class_metadata_factory'
            - '@apteka.infrastructure.redis'

    apteka.service.file:
        class: Xyz\Akulov\Symfony\Service\FileService\FileService
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@filesystem'
            - '@apteka.service.user'
            - '@validator.mapping.class_metadata_factory'
            - '/app/files'
            - '@monolog.logger'
        tags:
            - {name: monolog.logger, channel: apteka.service.file}

    apteka.service.task:
        class: Xyz\Akulov\Symfony\Service\TaskService\TaskService
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@apteka.service.user'
            - '@validator.mapping.class_metadata_factory'

    apteka.service.pharmacy_stock:
        class: Xyz\Akulov\Apteka\Symfony\Service\PharmacyStockService\PharmacyStockService
        arguments:
            - '@apteka.service.file'
            - '@apteka.service.task'
            - '@monolog.logger'
