Xyz\Akulov\Service\FileService\Entity\File:
    properties:
        name:
            - NotBlank: ~
            - Length: { min: 1, max: 255}
        hash:
            - NotBlank: ~
            - Length: { min: 64, max: 64}
        purpose:
            - NotBlank: ~
            - Length: { min: 1, max: 15}
            - Regex:
                pattern: '/^[a-z_]+$/i'
