Xyz\Akulov\Common\Entity\Group:
    type: entity
    table: groups

    id:
        id:
            type: integer
            generator:
              strategy: AUTO

    fields:
        name:
            type: string
            length: 32
            unique: true
