Xyz\Akulov\Common\Entity\User:
    type: entity
    table: users

    manyToMany:
        groups:
            targetEntity: Group
            joinTable:
                name: users_groups

    id:
        id:
            type: integer
            generator:
              strategy: AUTO

    fields:
        email:
            type: string
            length: 64
            unique: true
        passwordHash:
            type: string
            length: 64
